language: csharp
solution: Servicer.sln
mono:
  - beta
  - latest
script:
  - xbuild /p:Configuration=Release Servicer.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ServicerTests/bin/Release/ServicerTests.dll
  - nuget pack "Servicer.nuspec" -verbosity detailed -o Build -Version "1.0.0" -p Configuration="Release"
